Repository stephendawsondev/GrimManor, pull requests merged in 2023-10, with the labels that each got.

#10 Responsive scenario
  .DS_Store
  .gitignore
  assets/.DS_Store
  assets/css/style.css
  assets/images/scary-mansion.png
  assets/js/script.js
  index.html
Labels: must have

#13 Add hangman game initial structure
  .prettierrc
  assets/css/style.css
  assets/fonts/captain-howdy.ttf
  assets/images/ouija-board-blank.png
  assets/js/hangman.js
  assets/js/minigames/hangman.js
  assets/js/script.js
  index.html
Labels: enhancement

#22 Content of mainson separated to better testing and future integrating...
  assets/css/mansion.css
  assets/js/mansion.js
  mansion.html
Labels: duplicate

#26 Add instructions and dialogue
  assets/css/style.css
  assets/js/dialogue.js
  assets/js/script.js
  index.html
Labels: must have

#28 add ability to display dialogue in game container
  assets/css/style.css
  assets/js/dialogue.js
  assets/js/minigames/hangman.js
  assets/js/script.js
Labels: enhancement

#27 Add localstore functionality to save player data....
  .gitignore
  assets/js/gamedata-localstore.js
  mansion.html
Labels: should have

#29 Add instructions and dialogue
  assets/css/style.css
  assets/images/ghostly-man-image.png
  assets/js/dialogue.js
  assets/js/minigames/hangman.js
  assets/js/script.js
  index.html
Labels: must have

#30 Join code to follow with the integration of minigames in the mansion house...
  assets/css/mansion.css
  assets/css/style.css
  assets/js/mansion.js
  assets/js/minigames/memory-game.js
  assets/js/script.js
  index.html
  mansion.html
Labels: must have

#32 display memory game and update spelling
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: enhancement

#33 added keyboard movement to create interaction from guide image with interactive object…
  assets/css/style.css
  assets/images/guide.png
  assets/js/dialogue.js
  assets/js/script.js
  index.html
Labels: should have

#40 Added help image for accessing interactive objects in the mansion...
  assets/css/style.css
  assets/images/golden-magic.png
  assets/js/script.js
  index.html
  test/Repo-update.md
  test/index.html
  test/script1.js
  test/temp.html
  test/test1.css
  test/test1.html
  testlist.html
Labels: could have

#46 import memory game function and display modal on click
  .theia/launch.json
  .theia/settings.json
  assets/audio/classic-scare.mp3
  assets/audio/creepy-whistly-music.mp3
  assets/audio/dark-ambient-music.mp3
  assets/audio/door-creak-open.mp3
  assets/audio/evil-laugh.mp3
  assets/audio/ghost-scream.mp3
  assets/audio/high-pitched-scream.mp3
  assets/audio/spooky-ghost-wind.mp3
  assets/audio/stairs.mp3
  assets/audio/thunderstorm.mp3
  assets/audio/wind-and-dread.mp3
  assets/js/minigames/memory-game.js
  assets/js/script.js
  index.html
Labels: must have

#48 Integration to minigames done (and short changes)
  assets/js/minigames/quiz.js
  assets/js/quiz.js
  assets/js/script.js
  index.html
Labels: must have

#55 check parent for dialog instead of document, run once
  assets/js/dialogue.js
Labels: bug, must have

#57 add logic to display memory game
  assets/css/style.css
  assets/images/boy-ghost.webp
  assets/js/minigames/hangman.js
  assets/js/minigames/memory-game.js
  assets/js/script.js
Labels: enhancement

#59 add code for other audio
  assets/js/script.js
Labels: enhancement

#64 Localstore updated and lastquiz added...
  assets/css/style.css
  assets/images/card_back-dif.png
  assets/images/death_color-dif.png
  assets/images/justice_color-dif.png
  assets/images/lastquiz.jpg
  assets/images/the_fool_color-dif.png
  assets/images/the_hanged_man_color-dif.png
  assets/images/the_hermit_color-dif.png
  assets/images/the_moon_color-dif.png
  assets/js/gamedata-localstore.js
  assets/js/minigames/lastquiz.js
  assets/js/script.js
  index.html
  test/game.js
  test/lastquiz.css
  test/lastquiz.html
  test/lastquiz.js
  test/minigame4.html
  test/styles.css
Labels: must have

#66 add local storage check for memory and hangman
  assets/css/style.css
  assets/js/gamedata-localstore.js
  assets/js/minigames/hangman.js
  assets/js/minigames/memory-game.js
  assets/js/script.js
  landing.html
Labels: enhancement

#65 add fix for dialogue elements
  assets/js/dialogue.js
  assets/js/script.js
Labels: bug

#67 Fix errors, validate access to door2, add background image to lastquiz and quiz, changed door3 to stairs, works with localstores
  assets/css/style.css
  assets/js/gamedata-localstore.js
  assets/js/minigames/hangman.js
  assets/js/minigames/lastquiz.js
  assets/js/minigames/quiz.js
  assets/js/script.js
  index.html
Labels: must have

#70 fix dialogue
  assets/css/style.css
  assets/js/minigames/hangman.js
  assets/js/minigames/memory-game.js
Labels: bug

#71 add landing page to the init
  assets/css/style.css
  assets/js/gamedata-localstore.js
  assets/js/script.js
  landing.html
Labels: should have

#72 Add audio icons
  assets/css/style.css
  assets/images/music_off.webp
  assets/images/music_on.webp
  assets/images/sound_off.webp
  assets/images/sound_on.webp
  assets/js/gamedata-localstore.js
  assets/js/minigames/lastquiz.js
  assets/js/minigames/quiz.js
  assets/js/script.js
  index.html
  landing.html
Labels: bug, enhancement

#74 add dark ambient music to home
  assets/js/script.js
Labels: enhancement

#75 add wands displayed by default
  assets/css/style.css
Labels: could have

#78 fix problem to access to landing page when the page is reset
  assets/js/script.js
  landing.html
Labels: bug

#84 remove stop propagation event
  assets/js/script.js
Labels: bug

#85 fix dialgoue yet again, hopefully final time
  assets/js/dialogue.js
Labels: bug

#87 add chevron when the choices don't show
  assets/css/style.css
  assets/js/dialogue.js
  index.html
Labels: enhancement

#89 add an overlay and use percents for positions
  assets/css/style.css
  index.html
Labels: enhancement

#95 Corrections of audios to deploy
  assets/js/script.js
Labels: bug

#96 Code refactor
  assets/audio/door-creak-open.mp3
  assets/audio/door-shut.mp3
  assets/audio/door.mp3
  assets/audio/evil-laugh.mp3
  assets/css/style.css
  assets/js/minigames/hangman.js
  assets/js/minigames/lastquiz.js
  assets/js/minigames/memory-game.js
  assets/js/minigames/quiz.js
  assets/js/script.js
  assets/js/utils/audioSettings.js
  assets/js/utils/dialogueGeneration.js
  assets/js/utils/dialogues.js
  assets/js/utils/gamedataLocalstore.js
  index.html
  landing.html
Labels: enhancement

#97 Code refactor
  README.md
  assets/css/style.css
  assets/js/minigames/hangman.js
  assets/js/script.js
  assets/js/utils/audioSettings.js
  assets/js/utils/dialogueGeneration.js
  assets/js/utils/dialogues.js
  index.html
Labels: enhancement
